-- =====================================================
-- Ontario EV Grid Strain Analysis
-- Step 1: Database, Schema, Tables, and Stage Setup
-- =====================================================

USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS ELECTRIFICATION_READINESS;
CREATE SCHEMA IF NOT EXISTS ELECTRIFICATION_READINESS.PUBLIC;
CREATE SCHEMA IF NOT EXISTS ELECTRIFICATION_READINESS.STREAMLIT;

CREATE WAREHOUSE IF NOT EXISTS CUSTOMER_ANALYTICS_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE WAREHOUSE CUSTOMER_ANALYTICS_WH;
USE SCHEMA ELECTRIFICATION_READINESS.PUBLIC;

-- =====================================================
-- Base Tables
-- =====================================================

-- Ontario FSA geographic reference (586 FSAs)
CREATE TABLE IF NOT EXISTS ONTARIO_FSA (
    FSA VARCHAR(3) NOT NULL,
    LAT FLOAT,
    LON FLOAT,
    REGION VARCHAR(50),
    UTILITY VARCHAR(100),
    PRIMARY KEY (FSA)
);

-- EV registrations by FSA and quarter (Q1 2022 - Q4 2025)
CREATE TABLE IF NOT EXISTS EV_REGISTRATIONS (
    FSA VARCHAR(3) NOT NULL,
    QUARTER VARCHAR(10) NOT NULL,
    BEV_COUNT NUMBER(38,0),
    PHEV_COUNT NUMBER(38,0),
    TOTAL_EV NUMBER(38,0),
    PRIMARY KEY (FSA, QUARTER)
);

-- FSA demographics from Census 2021
CREATE TABLE IF NOT EXISTS FSA_DEMOGRAPHICS (
    FSA VARCHAR(3) NOT NULL,
    POPULATION NUMBER(38,0),
    TOTAL_DWELLINGS NUMBER(38,0),
    SINGLE_DETACHED NUMBER(38,0),
    APARTMENT_5PLUS NUMBER(38,0),
    MEDIAN_INCOME NUMBER(38,0),
    SEMI_DETACHED NUMBER(38,0),
    ROW_HOUSE NUMBER(38,0),
    APT_DUPLEX NUMBER(38,0),
    PRIMARY KEY (FSA)
);

-- IESO hourly residential demand by FSA (Dec 2024 - Nov 2025)
CREATE TABLE IF NOT EXISTS IESO_FSA_HOURLY_DEMAND (
    FSA VARCHAR(3) NOT NULL,
    HOUR NUMBER(38,0) NOT NULL,
    AVG_DAILY_KWH FLOAT,
    TOTAL_ANNUAL_KWH FLOAT,
    PREMISE_COUNT NUMBER(38,0),
    PRIMARY KEY (FSA, HOUR)
);

-- FSA polygon boundaries (Statistics Canada 2021 Census)
CREATE TABLE IF NOT EXISTS FSA_BOUNDARIES (
    FSA VARCHAR(10),
    GEOMETRY GEOGRAPHY
);

-- Modeled energy consumption per FSA
CREATE TABLE IF NOT EXISTS FSA_ENERGY_MODEL (
    FSA VARCHAR(3) NOT NULL,
    TOTAL_DWELLINGS NUMBER(38,0),
    SINGLE_DETACHED NUMBER(38,0),
    APT_TOTAL NUMBER(38,0),
    MODELED_ANNUAL_KWH NUMBER(38,0),
    AVG_KWH_PER_DWELLING FLOAT,
    PRIMARY KEY (FSA)
);

-- =====================================================
-- Internal Stage for Streamlit apps and data files
-- =====================================================

USE SCHEMA ELECTRIFICATION_READINESS.STREAMLIT;

CREATE STAGE IF NOT EXISTS STREAMLIT_STAGE
    DIRECTORY = (ENABLE = TRUE);
